spring:
  application:
    name: labboot-hibernate
  datasource:
    username: sa
    password: P@ssw0rd
    url: jdbc:sqlserver://localhost:1433;database=Rent;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  output:
    ansi:
      enabled: always
jwt:
  token:
    expire: 10
