spring:
  application:
    name: labboot-hibernate
  datasource:
    username: sa
    password: P@ssw0rd
    url: jdbc:sqlserver://localhost:1433;database=Rent;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 5MB   # 單個文件最大上傳大小
      max-request-size: 5MB # 整個請求最大上傳大小

jwt:
  token:
    expire: 100
